package com.zk.cabinet.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zk.cabinet.bean.Cabinet;
import com.zk.cabinet.bean.Dossier;
import com.zk.cabinet.bean.User;

import com.zk.cabinet.dao.CabinetDao;
import com.zk.cabinet.dao.DossierDao;
import com.zk.cabinet.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cabinetDaoConfig;
    private final DaoConfig dossierDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CabinetDao cabinetDao;
    private final DossierDao dossierDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cabinetDaoConfig = daoConfigMap.get(CabinetDao.class).clone();
        cabinetDaoConfig.initIdentityScope(type);

        dossierDaoConfig = daoConfigMap.get(DossierDao.class).clone();
        dossierDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cabinetDao = new CabinetDao(cabinetDaoConfig, this);
        dossierDao = new DossierDao(dossierDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Cabinet.class, cabinetDao);
        registerDao(Dossier.class, dossierDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cabinetDaoConfig.clearIdentityScope();
        dossierDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CabinetDao getCabinetDao() {
        return cabinetDao;
    }

    public DossierDao getDossierDao() {
        return dossierDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
